set(_CATKIN_CURRENT_PACKAGE "python_orocos_kdl")
set(python_orocos_kdl_VERSION "1.4.1")
set(python_orocos_kdl_MAINTAINER "Ruben Smits <ruben.smits@intermodalics.eu>")
set(python_orocos_kdl_PACKAGE_FORMAT "3")
set(python_orocos_kdl_BUILD_DEPENDS "orocos_kdl" "python" "python3")
set(python_orocos_kdl_BUILD_EXPORT_DEPENDS "python" "python3")
set(python_orocos_kdl_BUILDTOOL_DEPENDS "catkin")
set(python_orocos_kdl_BUILDTOOL_EXPORT_DEPENDS )
set(python_orocos_kdl_EXEC_DEPENDS "catkin" "orocos_kdl" "python" "python3")
set(python_orocos_kdl_RUN_DEPENDS "catkin" "orocos_kdl" "python" "python3")
set(python_orocos_kdl_TEST_DEPENDS "python-future" "python3-future" "python-psutil" "python3-psutil")
set(python_orocos_kdl_DOC_DEPENDS "python-sphinx")
set(python_orocos_kdl_URL_WEBSITE "http://wiki.ros.org/python_orocos_kdl")
set(python_orocos_kdl_URL_BUGTRACKER "")
set(python_orocos_kdl_URL_REPOSITORY "")
set(python_orocos_kdl_DEPRECATED "")